FILTRO = "/html/body/div/div[2]/div[2]/div/div[1]/div[3]/select"
NAME_A_Z = '/html/body/div/div[2]/div[2]/div/div[1]/div[3]/select/option[1]'
NAME_Z_A = '/html/body/div/div[2]/div[2]/div/div[1]/div[3]/select/option[2]'
PRICE_LOW_HI = '/html/body/div/div[2]/div[2]/div/div[1]/div[3]/select/option[3]'
PRICE_HI_LOW = '/html/body/div/div[2]/div[2]/div/div[1]/div[3]/select/option[4]'
INVENTARIO = "/html/body/div/div[2]/div[2]/div/div[2]/div"
ADD_TO_CART = "/html/body/div/div[2]/div[2]/div/div[2]/div/div[2]/div[3]/button"
ADD_TO_CART = "/html/body/div/div[2]/div[2]/div/div[2]/div/div[1]/div[3]/button"
CARRINHO ="/html/body/div/div[2]/div[1]/div[2]"
CHECKOUT = "/html/body/div/div[2]/div[3]/div/div[2]/a[2]"
NOME = "/html/body/div/div[2]/div[3]/div/form/div[1]/input[1]"
SOBRENOME = "/html/body/div/div[2]/div[3]/div/form/div[1]/input[2]"
ZIPCODE = "/html/body/div/div[2]/div[3]/div/form/div[1]/input[3]"
CONTINUAR_CHECKOUT = "/html/body/div/div[2]/div[3]/div/form/div[2]/input"
FINISH = "/html/body/div/div[2]/div[3]/div/div[2]/div[8]/a[2]"